<a href="https://colab.research.google.com/github/RengarajR404/Data-Science-Lab/blob/main/Data_Science_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Generate a tuple from the set ["aman", "222", 777, 400.4]

In [ ]:
set1={"aman", "222", 777, 400.4}
tuple1=tuple(set1)
print(tuple1)

('222', 'aman', 400.4, 777)


In [ ]:
bio_dictionary={"Roll No":"CB.EN.U4CSE20154","First Name":"Rengaraj","Last Name":"R ","Date of Birth":'01-4-2002'}
print(bio_dictionary.items())

dict_items([('Roll No', 'CB.EN.U4CSE20154'), ('First Name', 'Rengaraj'), ('Last Name', 'R '), ('Date of Birth', '01-4-2002')])


In [ ]:
import random
random.seed(10)
print(np.random.randn(3,3))

[[-1.07767185  0.08113879  2.37068404]
 [ 0.37099116  0.27886154 -0.73200321]
 [ 1.13105206  1.58206732  1.47196475]]


In [ ]:
list=[0.0,1.0]
print("Random number chosen: ",random.choice(list))
print("Absolute value of (-1234):",abs(-1234))

Random number chosen:  0.0
Absolute value of (-1234): 1234


In [ ]:
print("Random number: ",random.randint(20,90))

Random number:  74


In [ ]:
list=[11,12,13,14,15]
print("Sliced list: ",list[:3])
random.shuffle(list)
print("Shuffled list: ",list)
print("Random number chosen: ",random.choice(list))

Sliced list:  [11, 12, 13]
Shuffled list:  [15, 14, 11, 12, 13]
Random number chosen:  11


In [ ]:
string="The King is Dead, Long Live The King"
text_file = open("question.txt", "w")
text_file.write(string)
text_file.close()
text_file = open("question.txt", "r")
print("Contents of text file are as follows : ")
print(text_file.read())
text_file.close()

Contents of text file are as follows : 
The King is Dead, Long Live The King


In [ ]:
def illustration(a,b):
    if a==b:
        return 1
    elif a>b:
        return 2
    else:
        return 3
    
illustration(5,6)

3

In [ ]:
i=5
while i>0:
    if(i<=3):
        break
    if(i==2):
        continue
    for j in range(0,i):
        print("i= ",i)
        print("j= ",j)
    i=i-1

i=  5
j=  0
i=  5
j=  1
i=  5
j=  2
i=  5
j=  3
i=  5
j=  4
i=  4
j=  0
i=  4
j=  1
i=  4
j=  2
i=  4
j=  3


In [ ]:
string="The King is Dead, Long Live The King"
print("Complete text : ",string)
print("First Character : ",string[0])
print("Three Characters from 3rd to 5th element : ",string[3:5])
print("Starting from 3rd character : ",string[3:])
words=string.split(" ")
print("Spiltted words: ",words)

Complete text :  The King is Dead, Long Live The King
First Character :  T
Three Characters from 3rd to 5th element :   K
Starting from 3rd character :   King is Dead, Long Live The King
Spiltted words:  ['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [ ]:
array=np.array([1,2,3,4],dtype="float64")
print("Sliced array : ",array[:2])

Sliced array :  [1. 2.]


In [ ]:
two_d_array=([[1,2,3],[4,5,6]])
print("Two-Dimensional array : ",two_d_array)

Two-Dimensional array :  [[1, 2, 3], [4, 5, 6]]


In [ ]:
two_d_array=np.array([[1,2,3],[4,5,6]],dtype="float64")
print("2nd-row : ",two_d_array[1:2])
print("Next requirement : ",two_d_array[:,1:2].T)
print("Shape of array : ",two_d_array.shape)

2nd-row :  [[4. 5. 6.]]
Next requirement :  [[2. 5.]]
Shape of array :  (2, 3)


In [ ]:
new_array=np.array([1,2,3,4,5,6,7,8,9,10])
new_array=new_array.reshape(2,5)
print("Reshaped Array : ",new_array)
print("Transpose of Reshaped Array : ",new_array.T)

Reshaped Array :  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Transpose of Reshaped Array :  [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [ ]:
list=[1,2,3]
array=np.array(list)
print("Array from list : ",array)

Array from list :  [1 2 3]


In [ ]:
array=np.array([1,2,3])
list=[9,9,9]
print("Before filling : ",array)
array.fill(list[0])
print("After filling : ",array)

Before filling :  [1 2 3]
After filling :  [9 9 9]


In [ ]:
array=np.array([2,4,5])
print("Sum of elements = ",array.sum())

Sum of elements =  11


In [ ]:
array=np.array([77,74,75])
print("Product of elements = ",array.prod())

Product of elements =  427350


In [ ]:
array=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print("Mean : ",array.mean())
print("Min : ",array.min())
print("Max : ",array.max())
print("Median : ",np.median(array))
print("Argmax : ",array.argmax())
print("Argmin : ",array.argmin())
print("Standard Deviation : ",array.std())
print("Variance : ",array.var())

Mean :  12.461538461538462
Min :  1
Max :  56
Median :  2.0
Argmax :  12
Argmin :  1
Standard Deviation :  19.165736192147232
Variance :  367.32544378698225


In [ ]:
array=np.array([1, 1, 4, 5, 5, 5, 7])
uarray=np.unique(array)
uarray.sort()
print("Sorted array with unique elements : ",uarray)

Sorted array with unique elements :  [1 4 5 7]


In [ ]:
array1=np.array([1,2,3])
array2=np.array([0,1,1])
print("Dot product : ",np.dot(array1,array2))

Dot product :  5


In [ ]:
array=np.array([[2,-12],[1,-5]])
eigen_values,eigen_vector=np.linalg.eig(array)
print("Eigen Values : ",eigen_values)
print("Eigen Vector : ",eigen_vector)

Eigen Values :  [-1. -2.]
Eigen Vector :  [[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [ ]:
array=np.array([[11, 22, 11, 31], [25, 33, 31, 28]],dtype="float64")
print("Correlation Coefficients : ",np.corrcoef(array))

Correlation Coefficients :  [[1.         0.15997968]
 [0.15997968 1.        ]]
